<template>
  <div id="blog--post">
    <transition
      name="fade"
      mode="out-in"
      appear
      @before-enter="performPreProcessing"
      @after-enter="performPostProcessing">
      <section
        v-if="post"
        key="loaded">
        <div class="body">
          <div class="heading">
            <!-- Typography sizes in blog posts are off by one... -->
            <h1 class="blue-colored">{{ post.title }}</h1>
            <!-- ...so this h1 looks like an h2 -->
            <Metadata
              :absolute-date="post.publicationDate.absolute"
              :relative-date="post.publicationDate.relative"
              :tags="post.tags"/>
          </div>

          <div class="content" v-html="post.body" ref="content"></div>

          <p class="footer secondary-colored">
            Permalink to <a :href="post.portfolioUrl">this post</a>.
          </p>
        </div>
      </section>

      <section
        v-else
        key="loading"
        class="centered">
        <Spinner/>
      </section>
    </transition>
  </div>
</template>

<script>
  import prism from 'prismjs'
  import { mapActions, mapGetters } from 'vuex'

  import Spinner from '@/components/blog/spinner/Spinner'
  import Metadata from '@/components/blog/metadata/Metadata'

  import descriptions from '@/data/descriptions.json'

  /**
   * This is one blog post. It contains the complete content from the post.
   */
  export default {
    name: 'Post',
    metaInfo () {
      const post = this.post
      return {
        title: post ? post.title : 'Blog post',
        meta: ['description', 'og:description'].map(name => ({
          name,
          content: descriptions.blog
        }))
      }
    },
    components: {
      Spinner,
      Metadata
    },
    props: {
      /**
       * _the slug of the post to display_
       */
      slug: {
        type: String,
        required: true
      }
    },
    computed: {
      post () {
        return this.contentWithSlug(this.slug)
      },

      ...mapGetters('blog', [
        'contentWithSlug'
      ])
    },
    watch: {
      /**
       * Reload the page and the post content when the slug changes.
       * @param {string} to - the new value of the slug
       * @param {string} from - the old value of the slug
       */
      '$route.params.slug': function (to, from) {
        if (to !== from) { // No need to reload if nothing changes
          // Fetch new content from the API
          this.loadContent()
        }
      }
    },
    methods: {
      /**
       * Split all headings at the indices and color all indices in a slightly
       * muted color.
       */
      splitHeadings () {
        if (this.$refs.content) {
          const headings = this.$refs.content.querySelectorAll('h2, h3, h4, h5, h6')
          headings.forEach(heading => {
            const text = heading.innerText
            const html = text.replace(
              /^([\d.]+)/,
              '<span class="index">§$1</span>'
            )
            heading.innerHTML = html
          })
        }
      },
      /**
       * Highlight code snippets using Prism.
       */
      highlightCode () {
        prism.highlightAll()
      },

      /**
       * Perform processing to be done before the content is shown.
       */
      performPreProcessing () {
        this.splitHeadings()
      },
      /**
       * Perform processing to be done after the content is shown.
       */
      performPostProcessing () {
        this.highlightCode()
      },

      /**
       * Hit the serverless API for the portfolio and get the HTML content of
       * the blog. This HTML is automatically generated by Write.as from the
       * Markdown content of the post.
       */
      loadContent () {
        if (!this.contentWithSlug(this.slug)) {
          this.fetchContent({
            slug: this.slug
          })
        }
      },

      ...mapActions('blog', [
        'fetchContent'
      ])
    },
    mounted () {
      this.loadContent()
    }
  }
</script>

<style scoped lang="scss" src="./Post.scss"/>
